import { Script, ScriptEnv } from "system_lib/Script";
export declare class SamsungTVWebSocket extends Script {
    private ws;
    private tvHost;
    private tvPort;
    private useSSL;
    private authToken;
    private remoteName;
    private mPower;
    private mVolume;
    private mMuted;
    private mSource;
    private connecting;
    private connected;
    constructor(env: ScriptEnv);
    connect(host: string, port?: number, token?: string): Promise<void>;
    disconnect(): void;
    reconnect(): Promise<void>;
    private connectWebSocket;
    private handleMessage;
    private sendKey;
    private base64Encode;
    get isConnected(): boolean;
    get power(): boolean;
    set power(on: boolean);
    get volume(): number;
    set volume(level: number);
    get muted(): boolean;
    set muted(mute: boolean);
    get source(): string;
    set source(src: string);
    powerOn(): void;
    powerOff(): void;
    powerToggle(): void;
    volumeUp(): void;
    volumeDown(): void;
    toggleMute(): void;
    channelUp(): void;
    channelDown(): void;
    previousChannel(): void;
    up(): void;
    down(): void;
    left(): void;
    right(): void;
    enter(): void;
    back(): void;
    exit(): void;
    menu(): void;
    home(): void;
    tools(): void;
    info(): void;
    changeSource(): void;
    play(): void;
    pause(): void;
    stop(): void;
    rewind(): void;
    fastForward(): void;
    record(): void;
    sendCommand(key: string): void;
    selectHDMI(input: number): void;
    pressNumber(num: number): void;
    pictureMode(): void;
    pictureSize(): void;
}
