import { Script, ScriptEnv } from "system_lib/Script";
export declare class SamsungTVWebSocket extends Script {
    private tvConnections;
    private defaultTvId;
    private remoteName;
    private tokenFile;
    constructor(env: ScriptEnv);
    private loadTokens;
    private saveTokens;
    private getTVConnection;
    connect(host: string, port?: number, token?: string): Promise<void>;
    private connectWebSocket;
    disconnect(tvId?: string): void;
    private handleMessage;
    private sendKey;
    private base64Encode;
    get defaultTV(): string;
    set defaultTV(tvId: string);
    get connectedTVs(): string;
    powerOn(tvId?: string): Promise<void>;
    powerOff(tvId?: string): Promise<void>;
    powerToggle(tvId?: string): Promise<void>;
    volumeUp(tvId?: string): Promise<void>;
    volumeDown(tvId?: string): Promise<void>;
    toggleMute(tvId?: string): Promise<void>;
    channelUp(tvId?: string): Promise<void>;
    channelDown(tvId?: string): Promise<void>;
    previousChannel(tvId?: string): Promise<void>;
    up(tvId?: string): Promise<void>;
    down(tvId?: string): Promise<void>;
    left(tvId?: string): Promise<void>;
    right(tvId?: string): Promise<void>;
    enter(tvId?: string): Promise<void>;
    back(tvId?: string): Promise<void>;
    exit(tvId?: string): Promise<void>;
    menu(tvId?: string): Promise<void>;
    home(tvId?: string): Promise<void>;
    tools(tvId?: string): Promise<void>;
    info(tvId?: string): Promise<void>;
    changeSource(tvId?: string): Promise<void>;
    play(tvId?: string): Promise<void>;
    pause(tvId?: string): Promise<void>;
    stop(tvId?: string): Promise<void>;
    rewind(tvId?: string): Promise<void>;
    fastForward(tvId?: string): Promise<void>;
    record(tvId?: string): Promise<void>;
    sendCommand(key: string, tvId?: string): Promise<void>;
    selectHDMI(input: number, tvId?: string): Promise<void>;
    pressNumber(num: number, tvId?: string): Promise<void>;
    pictureMode(tvId?: string): Promise<void>;
    pictureSize(tvId?: string): Promise<void>;
    listTVs(): string;
}
