import { Driver } from "system_lib/Driver";
export declare class SamsungTV extends Driver<NetworkTCP> {
    protected socket: NetworkTCP;
    private mPower;
    private mVolume;
    private mMuted;
    private mSource;
    private readonly APP_STRING;
    private readonly REMOTE_NAME;
    private isAuthenticated;
    constructor(socket: NetworkTCP);
    protected onConnectStateChanged(connected: boolean): void;
    private authenticate;
    private handleResponse;
    private base64Encode;
    private sendKey;
    get power(): boolean;
    set power(on: boolean);
    get volume(): number;
    set volume(level: number);
    get muted(): boolean;
    set muted(mute: boolean);
    get source(): string;
    set source(src: string);
    powerOn(): void;
    powerOff(): void;
    powerToggle(): void;
    volumeUp(): void;
    volumeDown(): void;
    toggleMute(): void;
    channelUp(): void;
    channelDown(): void;
    previousChannel(): void;
    up(): void;
    down(): void;
    left(): void;
    right(): void;
    enter(): void;
    back(): void;
    exit(): void;
    menu(): void;
    home(): void;
    tools(): void;
    info(): void;
    changeSource(): void;
    play(): void;
    pause(): void;
    stop(): void;
    rewind(): void;
    fastForward(): void;
    record(): void;
    sendCommand(key: string): void;
    selectHDMI(input: number): void;
    pressNumber(num: number): void;
    pictureMode(): void;
    pictureSize(): void;
}
